### ISSUE TITLE
please help me!!

### ISSUE THREAD

**Issue by totallynotadi** [Kalebu/Commandline-chatting-system-python#1]
i've spent a whole day trying to figure out if i can connect to a remote socket in python. the server and client i have written work well when ran on the same machine or on different machines only if both are on the same network. what i intend to do is make it so that anyone in the world can connect to the server. please help me!!

**Comment by Kalebu** [comment]
Hello ,
If you're looking to host a socket server that can be hosted globally you
might wanna take a look at building tcp-socket-server,
You can easily do this with help of networking python libraries and
frameworks such as gevent, twisted and tornado

I personally did using tornado , Here is a starter on how it all works

https://github.com/Kalebu/real_time_tcp

Hope you will find that useful !!

**Comment by Kalebu** [comment]
Recommendation already given
